server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Automatically map service names to routes
      routes:
        - id: product-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: review-route
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
